name: Apply

on:
  workflow_call:
    inputs:
      destroy-args:
        description: Additional arguments to pass to the tofu destroy command.
        required: false
      init-args:
        description: Additional arguments to pass to the tofu init command.
        required: false
      use-primary-backend:
        description: Specifies whether to use the primary backend during initialization.
        required: true
        type: string
        default: 'true'
      version:
        description: The version of OpenTofu to install.
        required: true
        default: 1.8.1
      working-directory:
        description: The directory where the infrastructure code is located.
        required: true
        default: ./infrastructure
      workspace:
        description: The workspace to select or create during the apply process.
        required: true

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.oidc-role-arn }}
          aws-region: ${{ inputs.region }}
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.version }}
      - name: Init
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu init -no-color -lockfile=readonly -lock=false -var "use_primary_backend=${{ inputs.use-primary-backend }}" ${{ inputs.init-args }}
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Select workspace
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu workspace select -or-create=true "${{ inputs.workspace }}"
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Delete infrastructure
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu destroy -auto-approve -no-color -var "use_primary_backend=${{ inputs.use-primary-backend }}" ${{ inputs.destroy-args }}
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Delete workspace
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu workspace select default
          tofu workspace delete "${{ inputs.workspace }}"
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
