name: Plan

on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
      init-args:
        required: false
        type: string
      oidc-role-arn:
        required: true
        type: string
      plan-args:
        required: false
        type: string
      region:
        required: true
        type: string
      use-primary-backend:
        required: true
        type: boolean
        default: true
      version:
        required: false
        type: string
        default: 1.8.1
      working-directory:
        required: false
        type: string
        default: ./infrastructure
      workspace:
        required: true
        type: string

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.oidc-role-arn }}
          aws-region: ${{ inputs.region }}
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.version }}
      - name: Init
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu init -no-color -lockfile=readonly -lock=false -var "use_primary_backend=${{ inputs.use-primary-backend }}" ${{ inputs.init-args }}
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Select workspace
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu workspace select -or-create=true "${{ inputs.workspace }}"
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Plan
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu plan -no-color -out="plan.tfplan" -var "use_primary_backend=${{ inputs.use-primary-backend }}" ${{ inputs.plan-args }}
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Publish ${{ inputs.artifact-name }}
        if: ${{ inputs.artifact-name != '' }}
        uses: cupel-co/actions/artifact/upload@v0.5.0
        with:
          name: ${{ inputs.artifact-name }}
          overwrite: true
          path: ${{ inputs.working-directory }}
          retention-days: 1
  
  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:
      - plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.oidc-role-arn }}
          aws-region: ${{ inputs.region }}
      - name: Download ${{ inputs.artifact-name }}
        uses: cupel-co/actions/artifact/download@v0.5.0
        with:
          name: ${{ inputs.artifact-name }}
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.version }}
      - name: Apply
        shell: pwsh
        run: |
          ls -al
          tofu apply -no-color -auto-approve -lock=true ${{ inputs.apply-args }} "plan.tfplan"
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
