name: Plan and Apply

on:
  workflow_call:
    inputs:
      apply-args:
        description: Additional arguments to pass to the tofu apply command.
        required: false
        type: string
      artifact-name:
        description: The name of the artifact to upload after the plan step and download before the apply step.
        required: false
        type: string
      environment:
        description: The target environment where the apply operation will be executed (e.g., staging, production).
        required: true
        type: string
      init-args:
        description: Additional arguments to pass to the tofu init command.
        required: false
        type: string
      oidc-role-arn:
        description: The ARN of the OIDC role to assume for AWS credentials.
        required: true
        type: string
      plan-args:
        description: Additional arguments to pass to the tofu plan command.
        required: false
        type: string
      region:
        description: The AWS region to use for the plan and apply operations.
        required: true
        type: string
      use-primary-backend:
        description: Specifies whether to use the primary backend during initialization.
        required: true
        type: string
        default: 'true'
      version:
        description: The version of OpenTofu to install.
        required: false
        type: string
        default: 1.8.1
      working-directory:
        description: The directory where the infrastructure code is located.
        required: false
        type: string
        default: ./infrastructure
      workspace:
        description: The workspace to select or create during the plan and apply processes.
        required: true
        type: string
    secrets:
      apply-args:
        description: Additional arguments to pass to the tofu apply command.
        required: false
      init-args:
        description: Additional arguments to pass to the tofu init command.
        required: false
      plan-args:
        description: Additional arguments to pass to the tofu plan command.
        required: false

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.oidc-role-arn }}
          aws-region: ${{ inputs.region }}
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.version }}
      - name: Init
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu init -no-color -lockfile=readonly -lock=false -var "use_primary_backend=${{ inputs.use-primary-backend }}" ${{ inputs.init-args }} ${{ secrets.init-args }}
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Select workspace
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu workspace select -or-create=true "${{ inputs.workspace }}"
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Plan
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu plan -no-color -out="plan.tfplan" -var "use_primary_backend=${{ inputs.use-primary-backend }}" ${{ inputs.plan-args }} ${{ secrets.plan-args }}
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
      - name: Publish ${{ inputs.artifact-name }}
        if: ${{ inputs.artifact-name != '' }}
        uses: cupel-co/actions/artifact/upload@v0.5.0
        with:
          name: ${{ inputs.artifact-name }}
          overwrite: true
          path: ${{ inputs.working-directory }}
          retention-days: 1
  
  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:
      - plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.oidc-role-arn }}
          aws-region: ${{ inputs.region }}
      - name: Download ${{ inputs.artifact-name }}
        uses: cupel-co/actions/artifact/download@v0.5.0
        with:
          name: ${{ inputs.artifact-name }}
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.version }}
      - name: Apply
        shell: pwsh
        run: |
          ls -al
          tofu apply -no-color -auto-approve -lock=true ${{ inputs.apply-args }} ${{ secrets.apply-args }} "plan.tfplan"
        env:
          TF_IN_AUTOMATION: 1
          TF_INPUT: 0
