name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate
    uses: ./.github/workflows/generate-version.yml

  release:
    uses: ./.github/workflows/tag.yml
    needs:
      - generate
    name: Release
    permissions:
      contents: write
    with:
      tag: v${{ needs.generate.outputs.sem-ver }}
    secrets:
      gh-gpg-private-key: ${{ secrets.GH_GPG_PRIVATE_KEY }}
      gh-gpg-private-key-password: ${{ secrets.GH_GPG_PRIVATE_KEY_PASSWORD }}
      google-chat-webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
