name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    uses: ./.github/workflows/generate-version.yml

  production:
    uses: ./.github/workflows/tag.yml
    needs:
      - generate-version
    name: Production
    environment: Production
    env:
      tag: v${{ needs.generate-version.outputs.sem-ver }}
    with:
      tag: ${{ env.tag }}
    secrets:
      gh-gpg-private-key: ${{ secrets.GH_GPG_PRIVATE_KEY }}
      gh-gpg-private-key-password: ${{ secrets.GH_GPG_PRIVATE_KEY_PASSWORD }}
      google-chat-webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
